# Generated by Django 3.1.6 on 2021-04-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20210411_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedroute',
            name='routeNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
