# Generated by Django 3.1.6 on 2021-04-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_savedroute_routenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedroute',
            name='coordinates',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='savedroute',
            name='routeNumber',
            field=models.IntegerField(default=1),
        ),
    ]
