# Generated by Django 3.1.6 on 2021-04-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20210415_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedroute',
            name='routeNumber',
            field=models.IntegerField(default=0),
        ),
    ]
