# Generated by Django 3.1.6 on 2021-04-18 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0005_auto_20210415_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedroute',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='savedroute',
            unique_together={('owner', 'name')},
        ),
        migrations.RemoveField(
            model_name='savedroute',
            name='routeNumber',
        ),
    ]
