# Generated by Django 3.1.6 on 2021-04-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_auto_20210420_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='UVALocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.JSONField(default=dict)),
                ('properties', models.JSONField(default=dict)),
            ],
        ),
        migrations.RenameField(
            model_name='savedroute',
            old_name='coordinates',
            new_name='geojson',
        ),
    ]
