# Generated by Django 3.1.6 on 2021-04-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_uvalocation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UVALocationCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson', models.JSONField(default=dict)),
            ],
        ),
    ]
