# Generated by Django 3.1.6 on 2021-04-28 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0010_uvalocationcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_idea', models.TextField()),
                ('likes', models.ManyToManyField(related_name='recommendation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
