# Generated by Django 3.1.6 on 2021-05-02 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0012_remove_recommendation_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='location_idea',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='details',
            field=models.TextField(blank=True, default='No details provided', null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='likes',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='location_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('post_date', models.DateField(auto_now_add=True)),
                ('likes', models.JSONField(default=dict)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.recommendation')),
            ],
        ),
    ]
