# Generated by Django 3.1.6 on 2021-05-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_auto_20210501_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='location_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='location_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='location_longitude',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='location_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
