# Generated by Django 3.1.6 on 2021-05-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_auto_20210504_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
