# Generated by Django 3.1.6 on 2021-05-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_recommendation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='category',
            field=models.CharField(choices=[('College of Arts and Sciences', 'College of Arts and Sciences'), ('Dining', 'Dining'), ('Engineering School', 'Engineering School'), ('Library', 'Libraries'), ('Parking Garage', 'Parking'), ('Athletic', 'Athletic'), ('Housing', 'Housing'), ('Historical', 'Historical'), ('Batten School', 'Batten School'), ('McIntire School of Commerce', 'McIntire School of Commerce'), ('Music', 'Music'), ('Office', 'Office'), ('Research', 'Research'), ('School of Education', 'School of Education'), ('Architecture', 'Architecture'), ('Arts', 'Arts'), ('Law', 'Law'), ('Darden School of Business', 'Darden School of Business')], default='College of Arts and Sciences', max_length=30),
        ),
    ]
