# Generated by Django 3.1.6 on 2021-05-01 20:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0015_auto_20210501_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecommendationComment',
            new_name='Comment',
        ),
    ]
