# Generated by Django 3.1.6 on 2021-05-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0016_auto_20210501_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='details',
            field=models.TextField(blank=True, default='No details provided', null=True),
        ),
    ]
